spring:
  application:
    name: authentication-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9091