server:
  port: 8761

eureka:

  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 900000

  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/